### ISSUE TITLE
Section couverture

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#1]
### Créer la page de couverture du site web : 
- Respecter la charte : couleurs, polices, icône...
- Respecter le contenu (les textes qui sont déjà sur figma)

**Il faut que chaque élément de la barre de navigation redirige vers la section qui y correspond :** 
- **À propos : section 3 et 4

<img width="1190" alt="Capture d’écran 2024-05-15 à 09 35 28" src="https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/523b8666-3dec-45e4-b28d-cc524495a58c">

<img width="1190" alt="Capture d’écran 2024-05-15 à 09 35 43" src="https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/e6c8f083-45a9-4b41-928b-6f78f9989da7">

- **Archive** : section "RETOUR EN PHOTO" <img width="1143" alt="Capture d’écran 2024-05-11 à 19 45 36" src="https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/124571323/a815ae17-eec4-4aea-bf62-8af431314bc9">

- **FAQ** : section "FOIRE AUX QUESTIONS" <img width="1142" alt="Capture d’écran 2024-05-11 à 19 47 00" src="https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/124571323/b37e49d5-4d5a-495f-840a-e2574cfc11c2">

- **Inscription** : redirige vers une page d'inscription qui va se charger comme un pop up sur le site, les inscriptions doivent être enregistrés et envoyé directement par mail à whynotlinux@iteam-s.mg

- **Activités** : fait dérouler la liste des activités : Conférence, Stand, Salles d'exposition, Statistiques, Compétition. Chaque activité redirige vers la section de l'activité quand on clique dessus.

- Le bouton "Obtenir un billet" redirige vers la page d'inscription

- Le bouton "Devenir sponsor" redirige vers une page d'inscription qui se montrera comme un pop up sur le site. L'entreprise y ajoute son nom, ses coordonnées et la demande sera directement envoyé par mail à whynotlinux@iteam-s.mg afin que nous puissions leur envoyer par mail les documents nécessaires à remplir.

- Le QR code "inscrivez-vous" permet de générer la page d'inscription pour assister à l'évènement sur le téléphone pour que la personne puisse s'inscrire via son téléphone.

- La barre de navigation doit être collé tout en haut et y reste même quand on scrolle en bas.

**Comment by Damichou** [comment]
@razafindratsiza

**Comment by EmilieNirinasoa** [comment]
lay section foires aux questions nenah no ataoko

**Comment by Ntsoa2112** [comment]
I wanted to check in on the progress of this issue. Could you please provide an update on the section 'foires aux questions' @EmilieNirinasoa ?
