### ISSUE TITLE
Section organisateurs et partenaires

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#2]
### Créer la section organisateur et partenaire du site web : 
- Respecter la charte : couleurs, polices, icône...
- Respecter le contenu (les textes qui sont déjà sur figma)

Il faut qu'on puisse y rajouter des partenaires si le nombre de personnes qui veulent devenir partenaire augmentent. C'est à dire ne pas avoir un nombre de partenaire figé mais flexible selon notre besoin. 

![Uploading Capture d’écran 2024-05-11 à 21.06.54.png…]()

**Comment by NjNerson** [comment]
je prends cette section "organisateurs et partenaires"

![Capture d’écran du 2024-05-13 20-59-29](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/98582102/3dce6aad-d0cf-4b63-ac26-d75df7b31e0e)

**Comment by Damichou** [comment]
Mettre à jour la section organisateur. Voici la liste à jour des organisateurs :

- Iteam$ Community : https://drive.google.com/file/d/1zxS2TRoqQUEOuCynN675cZCyCPjOzvHz/view?usp=drivesdk
- Mada Linux Community : https://drive.google.com/file/d/1RE1Y9amvHL3Zz9gxWCWF80oW3pQAuZyA/view?usp=drivesdk
- EMITech Fianarantsoa : 
![IMG_4581](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/fe0f5bce-cc1f-40d5-aeee-3f4b8b104e80)
![IMG_4580](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/dfc819d6-6fbd-41f2-b4a6-e7794b305c9a)
- Club de Linux et Logiciel Libre de Fianarantsoa : 
![IMG_4579](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/52a40268-ae85-4193-9aea-ced5f7660afd)

Actuellement, nous n'avons qu'un seul partenaire qui est le GDG Antsirabe : 
![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/a439dc8b-11ce-47d5-a1d5-ebd9f8cccffd)

**Comment by Damichou** [comment]
@NjNerson je t'invite à prendre en compte mon dernier commentaire pour ta partie. Merci.

**Comment by NjNerson** [comment]
> @NjNerson je t'invite à prendre en compte mon dernier commentaire pour ta partie. Merci.

D'accord, je m'y mets

**Comment by NjNerson** [comment]
@Damichou ,pour le logo de C3LF,  on ne voit pas bien le logo à cause du fond blanc. Ce serais génial si nous avons un png avec. Merci

**Comment by Ntsoa2112** [comment]
![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/49555661/4b381735-4125-48d6-b9ae-4b0e26505e6e)
The title 'NOS PARTENAIRES' is too close to the separator. Could you add some space between the title and the separator? You can see this in the template. @NjNerson
