### ISSUE TITLE
Countdown section

### ISSUE THREAD

**Issue by rivo2302** [WhyNotLinuxMG/whynotlinuxmg.github.io#26]
Ajouter la sections pour la compte à rébour.

**_Maquette déjà disponible sur Figma._**

![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/59861055/46a44fde-2e9c-4628-bfb4-37cbc44cc368)

**Comment by ainafi** [comment]
i take this section

**Comment by Ntsoa2112** [comment]
![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/49555661/c4dc2253-cb25-45b8-8cf0-897f9ee3f02d)
Could you please improve the mobile version? Specifically, the text size should be reduced and the date should be centered.
