### ISSUE TITLE
Section type d'activité

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#3]
### Créer la section type d'activité du site web : 
- Respecter la charte : couleurs, polices, icône...
- Respecter le contenu (les textes qui sont déjà sur figma)

- **Conférence** : <img width="621" alt="Capture d’écran 2024-05-11 à 19 53 57" src="https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/124571323/33f2de9f-4baa-4a8e-b856-410555e683f3">

- **Stand** : <img width="1139" alt="Capture d’écran 2024-05-11 à 19 55 25" src="https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/124571323/19344438-39b6-4faf-b8a9-e5322461be21"> / pour cette partie, il faut qu'on puisse y rajouter des stands si le nombre de personnes qui veulent avoir des stands augmentent. C'est à dire ne pas avoir un nombre de stands figé mais flexible selon notre besoin. / Le bouton "Devenir sponsor" redirige vers une page d'inscription qui se montrera comme un pop up sur le site. L'entreprise y ajoute son nom, ses coordonnées et la demande sera directement envoyé par mail à whynotlinux@iteam-s.mg afin que nous puissions leur envoyer par mail les documents nécessaires à remplir.

- **Salles d'exposition** : ENCORE À METTRE À JOUR (je rajouterai les commentaires y afférent après les mises à jour)

- **Statistiques** : <img width="1158" alt="Capture d’écran 2024-05-11 à 19 58 03" src="https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/124571323/e29ba48f-5d01-43e4-bea3-28edf7d7bbe7"> / L'idéal serait que les chiffres bougent et fasse un décompte jusqu'à ce qu'ils arrivent au bon chiffre. Par exemple ça fait un décompte de 0 jusqu'à 350 pour le nombre de visiteurs.
 
- **Compétition** : <img width="1158" alt="Capture d’écran 2024-05-11 à 19 59 44" src="https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/124571323/6069755a-d067-4a74-ad54-f8a988bc52af"> / Il faut que le bouton "Participer à la compétition" redirige vers une page d'inscription qui se montrera comme un pop up sur le site. Sur la page d'inscription, la personne pourra choisir la compétition qui l'intéresse soit meme challenge, soit chasse au trésor, soit why not my desktop. La personne pourra après ajouter son contact fb et numéro pour qu'on puisse le contacter après. Les inscriptions doivent être enregistrés et envoyé directement par mail à whynotlinux@iteam-s.mg

**Comment by ainafi** [comment]
je prends cette section

**Comment by Ntsoa2112** [comment]
The mobile version still needs improvement for this issue. @ainafi
