### ISSUE TITLE
Section à propos

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#4]
### Créer la section à propos du site web : 
- Respecter la charte : couleurs, polices, icône...
- Respecter le contenu (les textes qui sont déjà sur figma)

<img width="1190" alt="Capture d’écran 2024-05-15 à 09 35 28" src="https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/7ff15e89-6def-4906-8090-ed700c728a98">

<img width="1190" alt="Capture d’écran 2024-05-15 à 09 35 43" src="https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/e6c8f083-45a9-4b41-928b-6f78f9989da7">

**Comment by NyFanasina** [comment]
Je prends celui-ci

**Comment by dorissylvie** [comment]
Je prends cette section "A propos"

**Comment by Damichou** [comment]
![Uploading Capture d’écran 2024-05-15 à 09.35.28.png…]()
![Uploading Capture d’écran 2024-05-15 à 09.35.43.png…]()

**Comment by Damichou** [comment]
![Uploading Capture d’écran 2024-05-15 à 09.35.28.png…]()
