### ISSUE TITLE
Menu non fonctionnel sur mobile

### ISSUE THREAD

**Issue by Ntsoa2112** [WhyNotLinuxMG/whynotlinuxmg.github.io#41]
Sur la version mobile, lorsque l'on clique sur l'icône du menu, rien ne se passe. Le menu devrait s'afficher mais ne le fait pas.

![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/49555661/26a863d1-5df8-47f6-acfb-d186017b6b26)
Le menu devrait apparaître après avoir cliqué sur l'icône.
Et aussi, il faut agrandir un peu l'image du pingouin.

**Comment by NjNerson** [comment]
Je prends cet issue
