### ISSUE TITLE
L'image au centre de carrousel doit être un peu plus grande

### ISSUE THREAD

**Issue by Ntsoa2112** [WhyNotLinuxMG/whynotlinuxmg.github.io#42]
![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/49555661/e1ee7895-cef6-4ba7-aa1c-933f4127048a)

L'image au centre de ce carrousel doit être un peu plus grande. Veuillez suivre le template fourni suivant:

![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/49555661/494c5e6d-54b7-41ba-bdfa-49f1963a6049)

**Comment by NjNerson** [comment]
c'est fait.
