### ISSUE TITLE
Réponses aux questions du FAQ

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#43]
<img width="897" alt="Capture d’écran 2024-05-31 à 09 56 25" src="https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/caa848a0-68ee-403a-b2f4-d0ad3b2ba5a2">

Quand-est-ce que l'évènement aura lieu ?
L'évènement aura lieu le 22 juin 2024.

Qui peut participer aux compétitions ?
Les compétitions sont ouvertes à toutes personnes passionnées d'informatique ou de technologie, ou simplement de personnes curieuses utilisant Linux.

Pour plus d'informations, qui puis-je contacter ?
Pous plus d'information, vous pouvez nous contacter en nous envoyant un mail à whynotlinux@iteam-s.mg ou nous envoyer un message sur notre page Why Not Linux.

Comment devenir sponsor ?
Pour devenir sponsor, il vous suffit de remplir la fiche de demande de sponsoring. ("fiche de demande de sponsoring", tu ajoutes un lien qui redirige vers la fiche d'inscription pour devenir sponsor. Demande à la personne chargé de faire la page de couverture le lien.)

**Comment by ainafi** [comment]
content changed !

**Comment by Damichou** [comment]
@ainafi 22 juin ilay date fa tsy 30 juin stp, merci.

**Comment by Ntsoa2112** [comment]
j'ai changé la date
