### ISSUE TITLE
Section salle d'exposition

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#44]
<img width="1680" alt="Capture d’écran 2024-05-31 à 10 09 05" src="https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/b6c68440-db17-4f62-a090-0e6bbe9d739a">

Séparer en 2 sections :

- Section 1 : **WNL 2.0 . Stand**
- Section 2 : **WNL 2.0 . Salle d'exposition**

Ny salle d'exposition efitra 1 ihany dia ao daholo no misy ny expo rehetra fa tsy ny stand rehetra akory dia misy daholo : 

- Question pour un champion + détails
- Défi de shell scripting + détails
- Desktop challenge + détails

Si possible dia zaraina colonne 3 ohatran'ny section stand dia ny anaran'ilay jeu no titre dia ny détails contenu.

**Comment by Ntsoa2112** [comment]
Je suis un peu perdu. Pourrais-tu nous expliquer plus en détail ce que nous devons faire ? @Damichou
