### ISSUE TITLE
Fautes d'orthographe

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#46]
Début de phrase mba atao majuscule fona svp : **Inscription, Devenir, Stand, Statistiques (avec s à la fin), Compétition**

Aza hadino ny accent fa lasa diso ilay mot sady tsy uniforme satria ny sasany misy ny sasany tsy misy : **TYPE D'ACTIVITÉ, Conférence, Démarquez-vous, Les chiffres clés de l'édition précédente, Compétition, Différents challenges à relever pour rendre cet évènement fun**

Ilay texte **"évènement"** mba apitovina daholo satria ny sasany "événement", lasa tsy uniforme ilay izy.

Autre faute : **5+ Merveilleux sponsors**

**Ilay date 22 juin fa tsy 30 juin**, amin'ilay type d'activité izao 30 juin no misoratra ao.

Lasa tapaka ilay lieu : 

- Antananarivo : Campus SESAME Ambatoroka
- Fianarantsoa : EMIT Andrainjato

![IMG_5267](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/124571323/d0f57cb2-57c5-4b6c-a3fc-35c709996ea8)

**Comment by Ntsoa2112** [comment]
Je prend ça

**Comment by Ntsoa2112** [comment]
Le nécessaire est fait @Damichou
