### ISSUE TITLE
Section ne ratez pas cet évènement

### ISSUE THREAD

**Issue by Damichou** [WhyNotLinuxMG/whynotlinuxmg.github.io#5]
### Créer la section "Ne ratez pas cet évènement" du site web : 
- Respecter la charte : couleurs, polices, icône...
- Respecter le contenu (les textes qui sont déjà sur figma)

- Le bouton "obtenir un billet" redirige vers une page d'inscription qui va se charger comme un pop up sur le site, les inscriptions doivent être enregistrés et envoyé directement par mail à whynotlinux@iteam-s.mg

**Comment by NyFanasina** [comment]
Je prends celui-ci

**Comment by Ntsoa2112** [comment]
The background still needs to be improved for this issue. The styles 0 1 0 1 are not critical; we just need to ensure the background color matches the template. Can you handle this, @NyFanasina ?
