### ISSUE TITLE
Responsivity issue on statistiques images white background

### ISSUE THREAD

**Issue by rootkit7628** [WhyNotLinuxMG/whynotlinuxmg.github.io#67]
![image](https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/assets/60097202/a3719fa6-2208-40fc-8c2a-a0cb2b208dd4)

Le fond blanc est colé avec l'image et se deplace avec.
Faudrait fixer l'image sur le container derrière peut-être.

**Comment by NjNerson** [comment]
je le prends
