### ISSUE TITLE
Home cover section

### ISSUE THREAD

**Issue by razafindratsiza** [WhyNotLinuxMG/whynotlinuxmg.github.io#7]
![MacBook Pro 16_ - 1](https://github.com/WhyNotLinuxMG/whynotlinux-website/assets/34934305/98b6d638-6cf5-4487-acc1-bc20ef926e68)

**Comment by razafindratsiza** [comment]
#I'm working on this one

**Comment by Damichou** [comment]
@razafindratsiza You should have commented on the issue “cover section” I created 4 days ago : https://github.com/WhyNotLinuxMG/whynotlinuxmg.github.io/issues/1#issue-2290280788

**Comment by Ntsoa2112** [comment]
I wanted to check in on the progress of this issue. Could you please provide an update on the current status? @razafindratsiza

**Comment by razafindratsiza** [comment]
> I wanted to check in on the progress of this issue. Could you please provide an update on the current status? @razafindratsiza

I'm working and trying to finish this section.
